name = "OkHypertextTools"
uuid = "ae1ef8a7-b62b-4b98-a332-ad23a8f1746c"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.1.1"

[deps]
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"

[compat]
HypertextLiteral = "0.9.5"
julia = "1.9"

[extras]
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "CompatHelperLocal"]
