name = "OkHypertextTools"
uuid = "ae1ef8a7-b62b-4b98-a332-ad23a8f1746c"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
